# Generated by Django 5.0.6 on 2024-06-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_address', models.TextField()),
                ('store_phone', models.CharField(max_length=15)),
                ('store_email', models.EmailField(max_length=100)),
                ('store_owner', models.CharField(max_length=100)),
                ('store_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
