# Generated by Django 5.0.6 on 2024-06-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompitatorAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serpresult',
            old_name='display_link',
            new_name='query',
        ),
        migrations.RemoveField(
            model_name='serpresult',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='serpresult',
            name='rank',
        ),
        migrations.AddField(
            model_name='serpresult',
            name='gl',
            field=models.CharField(default='us', max_length=10),
        ),
        migrations.AddField(
            model_name='serpresult',
            name='ranking_data',
            field=models.TextField(default=''),
        ),
    ]
