# Generated by Django 5.0.6 on 2024-06-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompitatorAnalysis', '0002_rename_display_link_serpresult_query_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serpresult',
            name='query',
            field=models.JSONField(max_length=255),
        ),
    ]
