# Generated by Django 5.0.6 on 2024-06-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompitatorAnalysis', '0003_alter_serpresult_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serpresult',
            name='query',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='serpresult',
            name='ranking_data',
            field=models.FileField(blank=True, null=True, upload_to='serp_rankings/'),
        ),
    ]
