# Generated by Django 5.0.6 on 2024-06-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompitatorAnalysis', '0004_alter_serpresult_query_alter_serpresult_ranking_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serpresult',
            name='query',
            field=models.JSONField(max_length=255),
        ),
    ]
