# Generated by Django 5.0.6 on 2024-06-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompitatorAnalysis', '0005_alter_serpresult_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serpresult',
            name='ranking_data',
        ),
        migrations.AddField(
            model_name='serpresult',
            name='Keywords',
            field=models.JSONField(default={}),
        ),
    ]
