# Generated by Django 5.0.6 on 2024-06-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompitatorAnalysis', '0006_remove_serpresult_ranking_data_serpresult_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serpresult',
            name='Keywords',
            field=models.JSONField(max_length=1000000),
        ),
    ]
