# Generated by Django 5.0.6 on 2024-06-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompitatorAnalysis', '0009_serpresult_link_serpresult_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serpresult',
            name='Keywords',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='serpresult',
            name='link',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='serpresult',
            name='query',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='serpresult',
            name='search_term',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
