# Generated by Django 5.0.6 on 2024-06-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompitatorAnalysis', '0010_alter_serpresult_keywords_alter_serpresult_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serpresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
