# Generated by Django 5.0.6 on 2024-06-29 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompitatorAnalysis', '0012_serpresult_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [


    ]
