# Generated by Django 5.0.6 on 2024-06-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompitatorAnalysis', '0013_serpresult_rank_serpresult_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serpresult',
            old_name='Keywords',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='serpresult',
            old_name='link',
            new_name='links',
        ),
        migrations.RenameField(
            model_name='serpresult',
            old_name='rank',
            new_name='ranks',
        ),
        migrations.RenameField(
            model_name='serpresult',
            old_name='search_term',
            new_name='search_terms',
        ),
    ]
