# Generated by Django 5.0.6 on 2024-06-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompitatorAnalysis', '0015_rename_image_serpresult_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serpresult',
            old_name='keywords',
            new_name='Keywords',
        ),
        migrations.RenameField(
            model_name='serpresult',
            old_name='links',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='serpresult',
            old_name='ranks',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='serpresult',
            old_name='search_terms',
            new_name='search_term',
        ),
        migrations.AddField(
            model_name='serpresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
