# Generated by Django 5.0.6 on 2024-06-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompitatorAnalysis', '0016_rename_keywords_serpresult_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serpresult',
            name='image',
            field=models.JSONField(default='', max_length=10000),
        ),
    ]
