# Generated by Django 5.0.6 on 2024-06-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompitatorAnalysis', '0017_alter_serpresult_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serpresult',
            name='image',
            field=models.JSONField(default=dict),
        ),
    ]
