# Generated by Django 5.0.6 on 2024-06-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompitatorAnalysis', '0018_alter_serpresult_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serpresult',
            name='image',
        ),
    ]
