# Generated by Django 5.0.6 on 2024-06-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyproducts', '0002_shopifyaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='admin_graphql_api_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='published_scope',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='template_suffix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='variants',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='shopify_product_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
