# Generated by Django 5.0.6 on 2024-06-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyproducts', '0003_products_admin_graphql_api_id_products_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_id',
            field=models.CharField(blank=True, max_length=76, null=True),
        ),
    ]
