# Generated by Django 5.0.6 on 2024-06-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyproducts', '0005_analyticsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
